---
title: "Mikroekonomi"
site: distill::distill_website
---


Nama mata kuliah: Mikroekonomi

Kode/SKS: PAGR2105/3SKS

Dosen: [Tedy Herlambang](https://bangtedy.github.io)

---

##	Deskripsi Matakuliah

Materi perkuliahan meliputi kelangkaan, biaya oportunitas, system ekonomi, struktur pasar produk, pasar faktor, kegagalan pasar, peran pemerintah di dalam perekonomian. Mahasiswa juga akan belajar bagaimana membuat, menginterpretasikan, memberi label dan menganalisis grafik dan data untuk menjelaskan konsep-konsep ekonomi.

##	Manfaat Matakuliah

Matakuliah ini akan memberi manfaat bagi mahasiswa dalam memahami dan mengimplementasikan sains dan seni analisis ekonomi

##	Tujuan Pembelajaran

Setelah mengikuti matakuliah ini, mahasiswa diharapkan mampu menggunakan mikroekonomi sebagai seni dan sains dalam menganalisis persoalan-persoalan ekonomi.

---

##	Strategi Perkuliahan

Perkuliahan dilakukan sebanyak 14 kali pertemuan dan 2 kali pertemuan untuk UTS dan UAS. Metode perkuliahan adalah kombinasi antara ceramah, diskusi, latihan dan presentasi kelompok. Mahasiswa wajib mengikuti perkuliahan minimal 80 persen.

## Kegiatan Pembelajaran

Pelaksanaan Pembelajaran Semester Genap Tahun Akademik 2O21/2O22 dilakukan dengan *Tatap Muka Terbatas*. Metode perkuliahan adalah kombinasi antara ceramah, diskusi, latihan dan presentasi kelompok. Mahasiswa harap memperhatikan pengumuman yang disampaikan dosen di WAG yang sudah dibentuk. 

Untuk dapat mengikuti perkuliahan dengan baik, mahasiswa sebaiknya membaca terlebih dahulu buku acuan pada bab-bab yang sesuai dengan materi pada minggu yang berkaitan dan mengerjakan tugas/latihan yang diberikan pada saat perkuliahan. Mahasiswa harus mereview semua bahan yang diberikan selama 14 kali untuk persiapan UTS dan UAS. 

## Referensi Utama

- McEachern, William A. (2019). Principiles of Microeconomics. Cengage Learning.
-	Besanko, D and Braeutigam, Ronald R., (2020). Microeconomics, 6th edition. John Wiley & Sons.

---

## Evaluasi dan Penilaian

Nilai Akhir untuk mata kuliah Kepemimpinan Agribisnis terdiri dari nilai ujian tengah semester (UTS), nilai ujian akhir semester (UAS) dan nilai komponen lain (KL). Nilai KL terdiri dari tugas individu, tugas kelompok, presentasi, kehadiran dan keaktifan. 

## Tugas Individu/Kelompok

Tugas diberikan pada saat kuliah dan wajib dikerjakan oleh mahasiswa dan
hasilnya dikumpulkan sesuai dengan waktu yang telah ditetapkan. Keterlambatan pengumpulan tugas akan mengurangi nilai sebesar 10 satuan per hari dengan batas maksimum keterlambatan 5 hari.

## Persebaran Nilai

1. UTS dan UAS dilakukan melalui ujian tertulis dengan bobot maksimum 60%

2. KL dinilai melalui keaktifan mahasiswa pada aktivitas pembelajaran (tugas-tugas, diskusi, presentasi dan kehadiran) dengan bobot 40%.

## Selang Penilaian

|No|Nilai|Bobot|Min|Max|Lulus|
|:---:|:---:|:---:|:---:|:---:|:---:|
|1  | A |4.00|80|100|Y|
|2  |B+|3.50|75|79.9|Y|
|3 | B |3.00 | 70|74.9|Y|
|4 | C+ | 2.75| 65| 69.9| Y|
|5|C|2.00|60|64.9|Y|
|6|D+|1.50| 55 |59.9| T|
|7|D|1| 45|54.9| T|
|8|E|0|0|44.9| T|

---

## Kejujuran Akademik dan Plagiarisme 

Mahasiswa harus mengikuti kebijakan dan aturan Universitas tentang kejujuran akademik dan plagiarisme seperti yang tertuang dalam pedoman akademik. Pelanggaran terhadap kebijakan tentang kejujuran akademik dan plagiarisme akan diberikan sanksi dari surat teguran, diberi nilai nol, skorsing sampai dikeluarkan dari Universitas.

## Kehadiran dan Disiplin Mahasiswa

Dalam hal perkuliahan dilakukan secara *luring*:

1. Hadir paling lambat 15 menit. Mahasiswa **TIDAK DIPERKENANKAN** masuk kelas setelah 15 menit kuliah dimulai.

2. Berpenampilan dan berbusana sopan serta rapi.

3. Tidak menggunakan sandal atau sejenisnya, serta tidak mengoperasikan ponsel/laptop kecuali diminta untuk keperluan perkualiahan.

4. Mahasiswa wajib mengikuti perkuliahan minimal 80 persen dari total 14 kali pertemuan, kecuali dengan alasan dan bukti yang valid.

5. Mahasiswa yang menyelesaikan kurang dari 50% tugas-tugas/ujian yang diberikan akan diberi nilai **E** (tidak lulus). 

6. Tidak ada ujian dan penugasan perbaikan.

---

## Tindak Kekerasan dan Pelecehan

Mahasiswa harus selalu menjaga sopan santun dan menghormati semua dosen, tenaga pendidikan, petugas keamanan, tenaga kesehatan dan sesama mahasiswa. Perilaku dan tindak kekerasan serta pelecehan yang mendisrupsi kegiatan pembelajaran, mengakibatkan kerusakan fasilitas dan properti kampus, akan diproses sesuai dengan aturan yang berlaku.

## Evaluasi Perkuliahan dan Dosen

Masukan mahasiswa untuk tujuan perbaikan perkuliahan akan diperhatikan dengan sangat serius. Mahasiswa sangat diharapkan menyisihkan waktu di setiap akhir semester untuk memberikan masukan dan evaluasi terkait dengan pelaksanaan perkuliahan dan dosen pengajar. Evaluasi dan masukan yang diberikan tidak akan mempengaruhi kelulusan dan nilai akhir.

## Teknologi yang Diperlukan

Teknologi yang diperlukan untuk perkuliahan ini adalah komputer dengan perangkat lunak yang mendukung, telepon seluler dan koneksi internet. 


